"""
COMPREHENSIVE MAHARASHTRA WATER QUALITY MONITORING STATIONS
Based on MPCB (Maharashtra Pollution Control Board) and GSDA (Groundwater Survey & Development Agency)

Station Types:
1. Surface Water Stations (Rivers, Lakes, Reservoirs, Coastal)
2. Groundwater Stations (Wells, Borewells, Piezometers)
3. Industrial Monitoring (STP, CETP, Effluent)

Monitoring Types:
- Baseline Stations (20 parameters, twice yearly)
- Trend Stations (14 parameters, twice yearly)
- Trend cum Surveillance Stations
"""

# ============================================
# SURFACE WATER MONITORING STATIONS (MPCB)
# ============================================

SURFACE_WATER_STATIONS = [
    # ==================== MUMBAI METROPOLITAN REGION ====================
    {
        'id': 'MH-MUM-SW-001',
        'name': 'Mithi River - Mahim',
        'stationType': 'Surface Water - River',
        'waterBody': 'Mithi River',
        'monitoringType': 'Trend cum Surveillance',
        'district': 'Mumbai',
        'taluka': 'Mumbai City',
        'region': 'Konkan',
        'latitude': 19.0369,
        'longitude': 72.8406,
        'altitude': 5,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Mumbai',
        'nearestCity': 'Mumbai',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban Dense',
        'designatedBestUse': 'Class-D (Wildlife & Fisheries)',
        'pollutionSources': ['Urban Runoff', 'Domestic Sewage', 'Industrial Effluent'],
        'industrialActivity': 'High',
        'baseParameters': {
            # Physicochemical
            'ph': 7.2,
            'temperature': 28.0,
            'turbidity': 18.0,
            'tds': 580.0,
            'conductivity': 920.0,
            'dissolvedOxygen': 5.2,
            'bod': 6.8,
            'cod': 35.0,
            'chlorides': 420.0,
            'totalHardness': 280.0,
            'totalAlkalinity': 190.0,
            'nitrates': 12.0,
            'phosphates': 2.5,
            'sulfates': 85.0,
            'fluoride': 0.8,
            'ammonia': 1.2,
            # Heavy Metals (mg/L)
            'iron': 0.8,
            'lead': 0.02,
            'chromium': 0.03,
            'arsenic': 0.008,
            'mercury': 0.0005,
            'cadmium': 0.003,
            # Microbiological (MPN/100ml)
            'totalColiform': 2400,
            'fecalColiform': 800,
        }
    },
    {
        'id': 'MH-MUM-SW-002',
        'name': 'Powai Lake',
        'stationType': 'Surface Water - Lake',
        'waterBody': 'Powai Lake',
        'monitoringType': 'Baseline Station',
        'district': 'Mumbai',
        'taluka': 'Kurla',
        'region': 'Konkan',
        'latitude': 19.1197,
        'longitude': 72.9059,
        'altitude': 15,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Mumbai',
        'nearestCity': 'Mumbai',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban',
        'designatedBestUse': 'Class-C (Drinking with treatment)',
        'pollutionSources': ['Urban Runoff', 'Religious Activities'],
        'industrialActivity': 'Medium',
        'baseParameters': {
            'ph': 7.4,
            'temperature': 26.5,
            'turbidity': 8.5,
            'tds': 380.0,
            'conductivity': 680.0,
            'dissolvedOxygen': 7.2,
            'bod': 3.2,
            'cod': 18.0,
            'chlorides': 280.0,
            'totalHardness': 220.0,
            'totalAlkalinity': 160.0,
            'nitrates': 6.5,
            'phosphates': 1.2,
            'sulfates': 55.0,
            'fluoride': 0.6,
            'ammonia': 0.4,
            'iron': 0.3,
            'lead': 0.005,
            'chromium': 0.01,
            'arsenic': 0.003,
            'mercury': 0.0001,
            'cadmium': 0.001,
            'totalColiform': 800,
            'fecalColiform': 150,
        }
    },
    {
        'id': 'MH-MUM-SW-003',
        'name': 'Bandra Reclamation - Arabian Sea',
        'stationType': 'Surface Water - Coastal',
        'waterBody': 'Arabian Sea',
        'monitoringType': 'Coastal Monitoring',
        'district': 'Mumbai',
        'taluka': 'Bandra',
        'region': 'Konkan',
        'latitude': 19.0596,
        'longitude': 72.8295,
        'altitude': 2,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Mumbai',
        'nearestCity': 'Mumbai',
        'populationNearby': 'Very High (>1,000,000)',
        'landUse': 'Urban Coastal',
        'designatedBestUse': 'Class-D (Marine Life)',
        'pollutionSources': ['Marine Traffic', 'Urban Runoff', 'Beach Activities'],
        'industrialActivity': 'Low',
        'baseParameters': {
            'ph': 7.8,
            'temperature': 27.0,
            'turbidity': 12.0,
            'tds': 450.0,
            'conductivity': 850.0,
            'dissolvedOxygen': 6.5,
            'bod': 4.5,
            'cod': 25.0,
            'chlorides': 380.0,
            'totalHardness': 260.0,
            'totalAlkalinity': 140.0,
            'nitrates': 8.5,
            'phosphates': 1.8,
            'sulfates': 95.0,
            'fluoride': 0.7,
            'ammonia': 0.8,
            'iron': 0.5,
            'lead': 0.008,
            'chromium': 0.015,
            'arsenic': 0.005,
            'mercury': 0.0003,
            'cadmium': 0.002,
            'totalColiform': 1200,
            'fecalColiform': 350,
        }
    },
    
    # ==================== THANE REGION ====================
    {
        'id': 'MH-THA-SW-001',
        'name': 'Ulhas River - Thane',
        'stationType': 'Surface Water - River',
        'waterBody': 'Ulhas River',
        'monitoringType': 'Trend Station',
        'district': 'Thane',
        'taluka': 'Thane',
        'region': 'Konkan',
        'latitude': 19.2183,
        'longitude': 72.9781,
        'altitude': 8,
        'samplingFrequency': 'Bi-monthly',
        'laboratory': 'GSDA Regional Lab - Thane',
        'nearestCity': 'Thane',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban',
        'designatedBestUse': 'Class-D (Wildlife & Fisheries)',
        'pollutionSources': ['Industrial Effluent', 'Domestic Sewage', 'Urban Runoff'],
        'industrialActivity': 'Very High',
        'baseParameters': {
            'ph': 7.2,
            'temperature': 27.5,
            'turbidity': 13.0,
            'tds': 470.0,
            'conductivity': 790.0,
            'dissolvedOxygen': 6.3,
            'bod': 5.0,
            'cod': 27.0,
            'chlorides': 370.0,
            'totalHardness': 290.0,
            'totalAlkalinity': 180.0,
            'nitrates': 9.8,
            'phosphates': 2.2,
            'sulfates': 78.0,
            'fluoride': 0.75,
            'ammonia': 1.0,
            'iron': 0.6,
            'lead': 0.015,
            'chromium': 0.025,
            'arsenic': 0.007,
            'mercury': 0.0004,
            'cadmium': 0.003,
            'totalColiform': 1800,
            'fecalColiform': 600,
        }
    },
    {
        'id': 'MH-THA-SW-002',
        'name': 'Tansa Lake',
        'stationType': 'Surface Water - Reservoir',
        'waterBody': 'Tansa Reservoir',
        'monitoringType': 'Baseline Station',
        'district': 'Thane',
        'taluka': 'Shahapur',
        'region': 'Konkan',
        'latitude': 19.7333,
        'longitude': 73.2333,
        'altitude': 120,
        'samplingFrequency': 'Monthly',
        'laboratory': 'GSDA Regional Lab - Thane',
        'nearestCity': 'Thane',
        'populationNearby': 'Low (<50,000)',
        'landUse': 'Forest/Protected',
        'designatedBestUse': 'Class-A (Drinking without treatment)',
        'pollutionSources': ['Minimal'],
        'industrialActivity': 'None',
        'baseParameters': {
            'ph': 7.6,
            'temperature': 24.0,
            'turbidity': 5.8,
            'tds': 310.0,
            'conductivity': 560.0,
            'dissolvedOxygen': 7.9,
            'bod': 2.3,
            'cod': 14.0,
            'chlorides': 210.0,
            'totalHardness': 180.0,
            'totalAlkalinity': 130.0,
            'nitrates': 5.2,
            'phosphates': 0.5,
            'sulfates': 35.0,
            'fluoride': 0.4,
            'ammonia': 0.2,
            'iron': 0.2,
            'lead': 0.002,
            'chromium': 0.005,
            'arsenic': 0.001,
            'mercury': 0.00005,
            'cadmium': 0.0005,
            'totalColiform': 50,
            'fecalColiform': 5,
        }
    },
    
    # ==================== PUNE REGION ====================
    {
        'id': 'MH-PUN-SW-001',
        'name': 'Mula River - Sangam Bridge',
        'stationType': 'Surface Water - River',
        'waterBody': 'Mula River',
        'monitoringType': 'Trend cum Surveillance',
        'district': 'Pune',
        'taluka': 'Pune City',
        'region': 'Pune',
        'latitude': 18.5277,
        'longitude': 73.8642,
        'altitude': 560,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Pune',
        'nearestCity': 'Pune',
        'populationNearby': 'Very High (>1,000,000)',
        'landUse': 'Urban Dense',
        'designatedBestUse': 'Class-C (Drinking with treatment)',
        'pollutionSources': ['Domestic Sewage', 'Industrial Effluent', 'Urban Runoff'],
        'industrialActivity': 'High',
        'baseParameters': {
            'ph': 7.3,
            'temperature': 25.0,
            'turbidity': 10.0,
            'tds': 420.0,
            'conductivity': 720.0,
            'dissolvedOxygen': 6.8,
            'bod': 4.0,
            'cod': 22.0,
            'chlorides': 320.0,
            'totalHardness': 250.0,
            'totalAlkalinity': 170.0,
            'nitrates': 9.0,
            'phosphates': 1.5,
            'sulfates': 62.0,
            'fluoride': 0.65,
            'ammonia': 0.7,
            'iron': 0.4,
            'lead': 0.008,
            'chromium': 0.018,
            'arsenic': 0.004,
            'mercury': 0.0002,
            'cadmium': 0.002,
            'totalColiform': 1400,
            'fecalColiform': 450,
        }
    },
    {
        'id': 'MH-PUN-SW-002',
        'name': 'Mutha River - Deccan',
        'stationType': 'Surface Water - River',
        'waterBody': 'Mutha River',
        'monitoringType': 'Trend Station',
        'district': 'Pune',
        'taluka': 'Pune City',
        'region': 'Pune',
        'latitude': 18.5074,
        'longitude': 73.8372,
        'altitude': 570,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Pune',
        'nearestCity': 'Pune',
        'populationNearby': 'Very High (>1,000,000)',
        'landUse': 'Urban',
        'designatedBestUse': 'Class-C (Drinking with treatment)',
        'pollutionSources': ['Domestic Sewage', 'Urban Runoff'],
        'industrialActivity': 'Medium',
        'baseParameters': {
            'ph': 7.4,
            'temperature': 24.5,
            'turbidity': 9.0,
            'tds': 400.0,
            'conductivity': 700.0,
            'dissolvedOxygen': 7.0,
            'bod': 3.8,
            'cod': 20.0,
            'chlorides': 300.0,
            'totalHardness': 240.0,
            'totalAlkalinity': 165.0,
            'nitrates': 8.0,
            'phosphates': 1.3,
            'sulfates': 58.0,
            'fluoride': 0.6,
            'ammonia': 0.6,
            'iron': 0.35,
            'lead': 0.006,
            'chromium': 0.012,
            'arsenic': 0.003,
            'mercury': 0.00015,
            'cadmium': 0.0015,
            'totalColiform': 1100,
            'fecalColiform': 380,
        }
    },
    {
        'id': 'MH-PUN-SW-003',
        'name': 'Khadakwasla Reservoir',
        'stationType': 'Surface Water - Reservoir',
        'waterBody': 'Khadakwasla Dam',
        'monitoringType': 'Baseline Station',
        'district': 'Pune',
        'taluka': 'Haveli',
        'region': 'Pune',
        'latitude': 18.4367,
        'longitude': 73.7584,
        'altitude': 595,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Pune',
        'nearestCity': 'Pune',
        'populationNearby': 'Medium (50,000-500,000)',
        'landUse': 'Semi-Urban',
        'designatedBestUse': 'Class-B (Outdoor bathing)',
        'pollutionSources': ['Tourism', 'Agricultural Runoff'],
        'industrialActivity': 'Low',
        'baseParameters': {
            'ph': 7.6,
            'temperature': 23.5,
            'turbidity': 6.5,
            'tds': 320.0,
            'conductivity': 580.0,
            'dissolvedOxygen': 7.8,
            'bod': 2.5,
            'cod': 15.0,
            'chlorides': 220.0,
            'totalHardness': 190.0,
            'totalAlkalinity': 140.0,
            'nitrates': 5.5,
            'phosphates': 0.8,
            'sulfates': 40.0,
            'fluoride': 0.5,
            'ammonia': 0.3,
            'iron': 0.25,
            'lead': 0.003,
            'chromium': 0.007,
            'arsenic': 0.002,
            'mercury': 0.0001,
            'cadmium': 0.001,
            'totalColiform': 200,
            'fecalColiform': 40,
        }
    },
    
    # ==================== NAGPUR REGION ====================
    {
        'id': 'MH-NAG-SW-001',
        'name': 'Nag River - Seminary Hills',
        'stationType': 'Surface Water - River',
        'waterBody': 'Nag River',
        'monitoringType': 'Trend cum Surveillance',
        'district': 'Nagpur',
        'taluka': 'Nagpur',
        'region': 'Vidarbha',
        'latitude': 21.1346,
        'longitude': 79.0820,
        'altitude': 310,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Nagpur',
        'nearestCity': 'Nagpur',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban',
        'designatedBestUse': 'Class-D (Wildlife & Fisheries)',
        'pollutionSources': ['Domestic Sewage', 'Industrial Effluent', 'Urban Runoff'],
        'industrialActivity': 'High',
        'baseParameters': {
            'ph': 7.1,
            'temperature': 27.5,
            'turbidity': 14.0,
            'tds': 480.0,
            'conductivity': 780.0,
            'dissolvedOxygen': 5.8,
            'bod': 5.2,
            'cod': 28.0,
            'chlorides': 350.0,
            'totalHardness': 300.0,
            'totalAlkalinity': 195.0,
            'nitrates': 10.5,
            'phosphates': 2.0,
            'sulfates': 72.0,
            'fluoride': 0.85,
            'ammonia': 0.9,
            'iron': 0.7,
            'lead': 0.012,
            'chromium': 0.022,
            'arsenic': 0.006,
            'mercury': 0.0003,
            'cadmium': 0.0025,
            'totalColiform': 1600,
            'fecalColiform': 550,
        }
    },
    {
        'id': 'MH-NAG-SW-002',
        'name': 'Ambazari Lake',
        'stationType': 'Surface Water - Lake',
        'waterBody': 'Ambazari Lake',
        'monitoringType': 'Baseline Station',
        'district': 'Nagpur',
        'taluka': 'Nagpur',
        'region': 'Vidarbha',
        'latitude': 21.1206,
        'longitude': 79.0473,
        'altitude': 305,
        'samplingFrequency': 'Monthly',
        'laboratory': 'MPCB Regional Lab - Nagpur',
        'nearestCity': 'Nagpur',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban Recreation',
        'designatedBestUse': 'Class-C (Drinking with treatment)',
        'pollutionSources': ['Urban Runoff', 'Recreation Activities'],
        'industrialActivity': 'Low',
        'baseParameters': {
            'ph': 7.5,
            'temperature': 26.0,
            'turbidity': 7.5,
            'tds': 360.0,
            'conductivity': 650.0,
            'dissolvedOxygen': 7.4,
            'bod': 3.0,
            'cod': 17.0,
            'chlorides': 260.0,
            'totalHardness': 210.0,
            'totalAlkalinity': 155.0,
            'nitrates': 6.8,
            'phosphates': 1.0,
            'sulfates': 48.0,
            'fluoride': 0.55,
            'ammonia': 0.5,
            'iron': 0.3,
            'lead': 0.005,
            'chromium': 0.01,
            'arsenic': 0.003,
            'mercury': 0.00012,
            'cadmium': 0.0012,
            'totalColiform': 600,
            'fecalColiform': 120,
        }
    },
]

# Continue with more stations...
# This is Phase 1A - I'll create the complete list in the next file

print(f"✅ Loaded {len(SURFACE_WATER_STATIONS)} Surface Water Monitoring Stations")
