"""
GROUNDWATER MONITORING STATIONS - GSDA (Groundwater Survey & Development Agency)
Based on: https://gsda.maharashtra.gov.in/en-groundwater-quality/

Total Network:
- 3,370 Baseline Stations (20 parameters, twice yearly)
- 975 Trend Stations (14 parameters, twice yearly)
- 183 Laboratories (6 Regional, 28 District, 144 Sub-divisional)
- 34 NABL accredited laboratories

Station Types:
- Dug Wells
- Borewells
- Piezometers

Sampling Schedule:
- Pre-Monsoon: April-May
- Post-Monsoon: October-November
"""

# ============================================
# GROUNDWATER BASELINE STATIONS (20 Parameters)
# ============================================

GROUNDWATER_BASELINE_STATIONS = [
    # ==================== MUMBAI SUBURBAN ====================
    {
        'id': 'MH-MUM-GW-BS-001',
        'name': 'Bhandup - Community Well',
        'stationType': 'Groundwater - Dug Well',
        'wellType': 'Dug Well',
        'monitoringType': 'Baseline Station',
        'district': 'Mumbai Suburban',
        'taluka': 'Kurla',
        'village': 'Bhandup',
        'region': 'Konkan',
        'latitude': 19.1434,
        'longitude': 72.9378,
        'altitude': 12,
        'wellDepth': 15.5,  # meters
        'waterLevel': 8.2,  # meters below ground level
        'aquiferType': 'Unconfined',
        'geologicalFormation': 'Basalt',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA Regional Lab - Mumbai',
        'nearestCity': 'Mumbai',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban Residential',
        'waterUsage': 'Domestic',
        'irrigationArea': 0,  # hectares
        'suitability': {
            'drinking': 'With Treatment',
            'irrigation': 'Suitable',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            # Physical Parameters
            'ph': 7.3,
            'temperature': 27.0,
            'turbidity': 4.5,
            'color': 5,  # Hazen units
            'odor': 'Absent',
            'taste': 'Agreeable',
            
            # Chemical Parameters
            'tds': 620.0,
            'conductivity': 980.0,
            'totalHardness': 340.0,
            'totalAlkalinity': 220.0,
            'calcium': 85.0,
            'magnesium': 42.0,
            'sodium': 95.0,
            'potassium': 8.5,
            'chlorides': 380.0,
            'sulfates': 68.0,
            'bicarbonates': 268.0,
            'nitrates': 28.0,
            'fluoride': 0.9,
            'iron': 0.8,
            'phosphates': 0.3,
            
            # Heavy Metals
            'arsenic': 0.008,
            'lead': 0.015,
            'chromium': 0.025,
            'cadmium': 0.004,
            
            # Microbiological
            'totalColiform': 25,
            'fecalColiform': 3,
        }
    },
    {
        'id': 'MH-MUM-GW-BS-002',
        'name': 'Mulund - Borewell Station',
        'stationType': 'Groundwater - Borewell',
        'wellType': 'Borewell',
        'monitoringType': 'Baseline Station',
        'district': 'Mumbai Suburban',
        'taluka': 'Kurla',
        'village': 'Mulund',
        'region': 'Konkan',
        'latitude': 19.1727,
        'longitude': 72.9565,
        'altitude': 18,
        'wellDepth': 45.0,
        'waterLevel': 18.5,
        'aquiferType': 'Confined',
        'geologicalFormation': 'Basalt - Fractured',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA Regional Lab - Mumbai',
        'nearestCity': 'Mumbai',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban Residential',
        'waterUsage': 'Domestic + Commercial',
        'irrigationArea': 0,
        'suitability': {
            'drinking': 'Suitable',
            'irrigation': 'Suitable',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            'ph': 7.5,
            'temperature': 25.5,
            'turbidity': 2.8,
            'color': 2,
            'odor': 'Absent',
            'taste': 'Agreeable',
            'tds': 480.0,
            'conductivity': 760.0,
            'totalHardness': 280.0,
            'totalAlkalinity': 185.0,
            'calcium': 72.0,
            'magnesium': 35.0,
            'sodium': 68.0,
            'potassium': 6.5,
            'chlorides': 290.0,
            'sulfates': 52.0,
            'bicarbonates': 225.0,
            'nitrates': 18.0,
            'fluoride': 0.7,
            'iron': 0.4,
            'phosphates': 0.2,
            'arsenic': 0.004,
            'lead': 0.008,
            'chromium': 0.012,
            'cadmium': 0.002,
            'totalColiform': 10,
            'fecalColiform': 0,
        }
    },
    
    # ==================== THANE DISTRICT ====================
    {
        'id': 'MH-THA-GW-BS-001',
        'name': 'Kalyan - Agricultural Well',
        'stationType': 'Groundwater - Dug Well',
        'wellType': 'Dug Well',
        'monitoringType': 'Baseline Station',
        'district': 'Thane',
        'taluka': 'Kalyan',
        'village': 'Kalyan East',
        'region': 'Konkan',
        'latitude': 19.2403,
        'longitude': 73.1305,
        'altitude': 22,
        'wellDepth': 18.0,
        'waterLevel': 9.5,
        'aquiferType': 'Unconfined',
        'geologicalFormation': 'Alluvium over Basalt',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA District Lab - Thane',
        'nearestCity': 'Kalyan',
        'populationNearby': 'Medium (50,000-500,000)',
        'landUse': 'Agricultural',
        'waterUsage': 'Irrigation + Domestic',
        'irrigationArea': 12.5,
        'suitability': {
            'drinking': 'With Treatment',
            'irrigation': 'Suitable',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            'ph': 7.2,
            'temperature': 26.0,
            'turbidity': 6.2,
            'color': 8,
            'odor': 'Absent',
            'taste': 'Agreeable',
            'tds': 580.0,
            'conductivity': 920.0,
            'totalHardness': 310.0,
            'totalAlkalinity': 205.0,
            'calcium': 80.0,
            'magnesium': 38.0,
            'sodium': 82.0,
            'potassium': 9.0,
            'chlorides': 340.0,
            'sulfates': 64.0,
            'bicarbonates': 250.0,
            'nitrates': 35.0,
            'fluoride': 0.8,
            'iron': 1.2,
            'phosphates': 0.5,
            'arsenic': 0.006,
            'lead': 0.01,
            'chromium': 0.018,
            'cadmium': 0.003,
            'totalColiform': 45,
            'fecalColiform': 8,
        }
    },
    {
        'id': 'MH-THA-GW-BS-002',
        'name': 'Bhiwandi - Industrial Borewell',
        'stationType': 'Groundwater - Borewell',
        'wellType': 'Borewell',
        'monitoringType': 'Baseline Station',
        'district': 'Thane',
        'taluka': 'Bhiwandi',
        'village': 'Bhiwandi',
        'region': 'Konkan',
        'latitude': 19.3009,
        'longitude': 73.0630,
        'altitude': 16,
        'wellDepth': 55.0,
        'waterLevel': 22.0,
        'aquiferType': 'Confined',
        'geologicalFormation': 'Basalt - Fractured',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA District Lab - Thane',
        'nearestCity': 'Bhiwandi',
        'populationNearby': 'Medium (50,000-500,000)',
        'landUse': 'Industrial',
        'waterUsage': 'Industrial + Domestic',
        'irrigationArea': 0,
        'suitability': {
            'drinking': 'Not Suitable',
            'irrigation': 'Marginal',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            'ph': 7.0,
            'temperature': 27.5,
            'turbidity': 8.5,
            'color': 12,
            'odor': 'Slight',
            'taste': 'Slightly Objectionable',
            'tds': 720.0,
            'conductivity': 1140.0,
            'totalHardness': 380.0,
            'totalAlkalinity': 240.0,
            'calcium': 95.0,
            'magnesium': 48.0,
            'sodium': 120.0,
            'potassium': 11.0,
            'chlorides': 450.0,
            'sulfates': 95.0,
            'bicarbonates': 292.0,
            'nitrates': 52.0,
            'fluoride': 1.2,
            'iron': 1.8,
            'phosphates': 0.8,
            'arsenic': 0.012,
            'lead': 0.022,
            'chromium': 0.035,
            'cadmium': 0.006,
            'totalColiform': 120,
            'fecalColiform': 35,
        }
    },
    
    # ==================== PUNE DISTRICT ====================
    {
        'id': 'MH-PUN-GW-BS-001',
        'name': 'Hadapsar - Community Borewell',
        'stationType': 'Groundwater - Borewell',
        'wellType': 'Borewell',
        'monitoringType': 'Baseline Station',
        'district': 'Pune',
        'taluka': 'Haveli',
        'village': 'Hadapsar',
        'region': 'Pune',
        'latitude': 18.5018,
        'longitude': 73.9263,
        'altitude': 580,
        'wellDepth': 60.0,
        'waterLevel': 25.0,
        'aquiferType': 'Confined',
        'geologicalFormation': 'Basalt',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA Regional Lab - Pune',
        'nearestCity': 'Pune',
        'populationNearby': 'High (>500,000)',
        'landUse': 'Urban Residential',
        'waterUsage': 'Domestic + Commercial',
        'irrigationArea': 0,
        'suitability': {
            'drinking': 'Suitable',
            'irrigation': 'Suitable',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            'ph': 7.4,
            'temperature': 24.5,
            'turbidity': 3.2,
            'color': 3,
            'odor': 'Absent',
            'taste': 'Agreeable',
            'tds': 520.0,
            'conductivity': 820.0,
            'totalHardness': 295.0,
            'totalAlkalinity': 195.0,
            'calcium': 76.0,
            'magnesium': 36.0,
            'sodium': 75.0,
            'potassium': 7.5,
            'chlorides': 310.0,
            'sulfates': 58.0,
            'bicarbonates': 238.0,
            'nitrates': 22.0,
            'fluoride': 0.75,
            'iron': 0.5,
            'phosphates': 0.25,
            'arsenic': 0.005,
            'lead': 0.009,
            'chromium': 0.015,
            'cadmium': 0.0025,
            'totalColiform': 15,
            'fecalColiform': 2,
        }
    },
    {
        'id': 'MH-PUN-GW-BS-002',
        'name': 'Baramati - Agricultural Well',
        'stationType': 'Groundwater - Dug Well',
        'wellType': 'Dug Well',
        'monitoringType': 'Baseline Station',
        'district': 'Pune',
        'taluka': 'Baramati',
        'village': 'Baramati',
        'region': 'Pune',
        'latitude': 18.1515,
        'longitude': 74.5815,
        'altitude': 530,
        'wellDepth': 22.0,
        'waterLevel': 11.0,
        'aquiferType': 'Unconfined',
        'geologicalFormation': 'Basalt',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA District Lab - Pune',
        'nearestCity': 'Baramati',
        'populationNearby': 'Low (<50,000)',
        'landUse': 'Agricultural',
        'waterUsage': 'Irrigation + Domestic',
        'irrigationArea': 25.0,
        'suitability': {
            'drinking': 'With Treatment',
            'irrigation': 'Suitable',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            'ph': 7.6,
            'temperature': 25.0,
            'turbidity': 5.8,
            'color': 7,
            'odor': 'Absent',
            'taste': 'Agreeable',
            'tds': 640.0,
            'conductivity': 1010.0,
            'totalHardness': 350.0,
            'totalAlkalinity': 230.0,
            'calcium': 88.0,
            'magnesium': 44.0,
            'sodium': 92.0,
            'potassium': 10.5,
            'chlorides': 380.0,
            'sulfates': 72.0,
            'bicarbonates': 280.0,
            'nitrates': 45.0,
            'fluoride': 1.0,
            'iron': 1.5,
            'phosphates': 0.6,
            'arsenic': 0.007,
            'lead': 0.012,
            'chromium': 0.02,
            'cadmium': 0.004,
            'totalColiform': 55,
            'fecalColiform': 12,
        }
    },
    
    # ==================== NAGPUR DISTRICT ====================
    {
        'id': 'MH-NAG-GW-BS-001',
        'name': 'Kamptee - Piezometer Station',
        'stationType': 'Groundwater - Piezometer',
        'wellType': 'Piezometer',
        'monitoringType': 'Baseline Station',
        'district': 'Nagpur',
        'taluka': 'Kamptee',
        'village': 'Kamptee',
        'region': 'Vidarbha',
        'latitude': 21.2231,
        'longitude': 79.2004,
        'altitude': 295,
        'wellDepth': 35.0,
        'waterLevel': 15.5,
        'aquiferType': 'Semi-Confined',
        'geologicalFormation': 'Basalt',
        'samplingFrequency': 'Twice Yearly (Pre & Post Monsoon)',
        'laboratory': 'GSDA Regional Lab - Nagpur',
        'nearestCity': 'Nagpur',
        'populationNearby': 'Medium (50,000-500,000)',
        'landUse': 'Mixed Agricultural-Urban',
        'waterUsage': 'Monitoring Only',
        'irrigationArea': 0,
        'suitability': {
            'drinking': 'Suitable',
            'irrigation': 'Suitable',
            'industrial': 'Suitable'
        },
        'baseParameters': {
            'ph': 7.3,
            'temperature': 26.5,
            'turbidity': 3.5,
            'color': 4,
            'odor': 'Absent',
            'taste': 'Agreeable',
            'tds': 560.0,
            'conductivity': 880.0,
            'totalHardness': 320.0,
            'totalAlkalinity': 210.0,
            'calcium': 82.0,
            'magnesium': 40.0,
            'sodium': 80.0,
            'potassium': 8.0,
            'chlorides': 330.0,
            'sulfates': 65.0,
            'bicarbonates': 256.0,
            'nitrates': 26.0,
            'fluoride': 1.1,
            'iron': 0.9,
            'phosphates': 0.4,
            'arsenic': 0.009,
            'lead': 0.011,
            'chromium': 0.019,
            'cadmium': 0.003,
            'totalColiform': 20,
            'fecalColiform': 3,
        }
    },
]

# Continue in next file...
print(f"✅ Loaded {len(GROUNDWATER_BASELINE_STATIONS)} Groundwater Baseline Stations")
