import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'dart:typed_data';

class ReportService {
  /// Generate PDF Report
  static Future<Uint8List> generatePDFReport({
    required String title,
    required String organization,
    required List<Map<String, dynamic>> data,
    required String generatedBy,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final formatter = DateFormat('yyyy-MM-dd HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Header
          pw.Header(
            level: 0,
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'PureHealth Water Quality Report',
                  style: pw.TextStyle(
                    fontSize: 28,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 5),
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 18,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Report Info
          pw.Container(
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
            ),
            padding: const pw.EdgeInsets.all(15),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Organization',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey600,
                      ),
                    ),
                    pw.Text(organization),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Generated Date',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey600,
                      ),
                    ),
                    pw.Text(formatter.format(now)),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Records',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey600,
                      ),
                    ),
                    pw.Text('${data.length}'),
                  ],
                ),
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Generated By',
                      style: pw.TextStyle(
                        fontSize: 10,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey600,
                      ),
                    ),
                    pw.Text(generatedBy),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 30),

          // Summary Stats
          pw.Text(
            'Summary Statistics',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Row(
            children: [
              _buildStatBox('Safe', _countStatus(data, 'Safe'), PdfColors.green),
              pw.SizedBox(width: 10),
              _buildStatBox('Warning', _countStatus(data, 'Warning'), PdfColors.orange),
              pw.SizedBox(width: 10),
              _buildStatBox('Critical', _countStatus(data, 'Critical'), PdfColors.red),
            ],
          ),
          pw.SizedBox(height: 30),

          // Data Table
          pw.Text(
            'Water Quality Data',
            style: pw.TextStyle(
              fontSize: 16,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            columnWidths: {
              0: const pw.FlexColumnWidth(1.5),
              1: const pw.FlexColumnWidth(1),
              2: const pw.FlexColumnWidth(1.2),
              3: const pw.FlexColumnWidth(1.5),
              4: const pw.FlexColumnWidth(1.5),
            },
            children: [
              // Header row
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: [
                  _buildTableCell('Location', bold: true),
                  _buildTableCell('pH', bold: true),
                  _buildTableCell('Turbidity', bold: true),
                  _buildTableCell('Temperature', bold: true),
                  _buildTableCell('Status', bold: true),
                ],
              ),
              // Data rows
              ...data.map((row) {
                final status = row['status'] ?? 'Unknown';
                final statusColor = status == 'Safe'
                    ? PdfColors.green
                    : status == 'Warning'
                        ? PdfColors.orange
                        : PdfColors.red;

                return pw.TableRow(
                  children: [
                    _buildTableCell(row['location']?.toString() ?? 'N/A'),
                    _buildTableCell((row['pH'] as num?)?.toStringAsFixed(1) ?? 'N/A'),
                    _buildTableCell(
                      (row['turbidity'] as num?)?.toStringAsFixed(1) ?? 'N/A',
                    ),
                    _buildTableCell(
                      '${(row['temperature'] as num?)?.toStringAsFixed(1) ?? 'N/A'}°C',
                    ),
                    pw.Container(
                      padding: const pw.EdgeInsets.all(5),
                      decoration: pw.BoxDecoration(
                        color: PdfColors.grey100,
                        border: pw.Border.all(color: statusColor),
                        borderRadius: const pw.BorderRadius.all(
                          pw.Radius.circular(3),
                        ),
                      ),
                      child: pw.Center(
                        child: pw.Text(
                          status,
                          style: pw.TextStyle(
                            fontSize: 9,
                            color: statusColor,
                            fontWeight: pw.FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                  ],
                );
              }).toList(),
            ],
          ),
          pw.SizedBox(height: 30),

          // Recommendations
pw.Text(
  'Recommendations',
  style: pw.TextStyle(
    fontSize: 16,
    fontWeight: pw.FontWeight.bold,
  ),
),
pw.SizedBox(height: 10),
pw.Column(
  children: _generateRecommendations(data)
      .map(
        (rec) => pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('• ', style: pw.TextStyle(fontSize: 10)),
              pw.SizedBox(width: 5),
              pw.Flexible(
                child: pw.Text(
                  rec,
                  style: pw.TextStyle(fontSize: 10),
                ),
              ),
            ],
          ),
        ),
      )
      .toList(),
),

          pw.SizedBox(height: 30),

          // Footer
          pw.Divider(),
          pw.SizedBox(height: 10),
          pw.Text(
            'This report was generated by PureHealth Water Quality Management System',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  /// Generate CSV Export
  static String generateCSVReport(List<Map<String, dynamic>> data) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('Location,pH,Turbidity,DissolvedOxygen,Temperature,Conductivity,Status,Timestamp');

    // Data rows
    for (final row in data) {
      buffer.writeln(
        '${row['location']},${row['pH']},${row['turbidity']},${row['dissolved_oxygen']},${row['temperature']},${row['conductivity']},${row['status']},${row['timestamp']}',
      );
    }

    return buffer.toString();
  }

  /// Generate Excel Export
  static Future<Uint8List> generateExcelReport(
    List<Map<String, dynamic>> data,
  ) async {
    // This would use the excel package
    // For now, return CSV as bytes
    final csv = generateCSVReport(data);
    return Uint8List.fromList(csv.codeUnits);
  }

  // Helper functions
  static pw.Widget _buildStatBox(String label, int count, PdfColor color) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(10),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: color),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
        ),
        child: pw.Column(
          children: [
            pw.Text(
              label,
              style: pw.TextStyle(
                fontSize: 10,
                fontWeight: pw.FontWeight.bold,
                color: color,
              ),
            ),
            pw.Text(
              '$count',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: color,
              ),
            ),
          ],
        ),
      ),
    );
  }

  static pw.Widget _buildTableCell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 9,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  static int _countStatus(List<Map<String, dynamic>> data, String status) {
    return data.where((item) => item['status'] == status).length;
  }

  static List<String> _generateRecommendations(List<Map<String, dynamic>> data) {
    final critical = _countStatus(data, 'Critical');
    final warning = _countStatus(data, 'Warning');

    final recs = <String>[];

    if (critical > 0) {
      recs.add('URGENT: $critical location(s) have critical water quality issues. Immediate action required.');
    }
    if (warning > 0) {
      recs.add('$warning location(s) have warning-level issues. Increase monitoring and review treatment.');
    }
    if (critical == 0 && warning == 0) {
      recs.add('All monitored locations are within safe parameters. Continue routine monitoring.');
    }

    recs.add('Maintain regular testing schedules and update data regularly.');
    recs.add('Document all treatment actions and their outcomes.');
    recs.add('Review historical trends to identify seasonal patterns.');

    return recs;
  }
}
